### ISSUE TITLE
BuilderConstraint has a default of 0.0 for minValue but it is ignored

### ISSUE THREAD

**Issue by MattTYXM** [DavidBurkett/Builderberg#15]
BuilderConstraint has a default of 0.0 for minValue but it is ignored. For instance the generated validate method has no content if I simply annotate a double field with @BuilderConstraint

**Comment by DavidBurkett** [comment]
It has a default of 0.0 just so you don't have to always define that if you're not interested in setting a minValue. It won't actually validate the minValue unless you specify it manually, though. This is implemented this way by design.
