### ISSUE TITLE
Add support for custom generated code

### ISSUE THREAD

**Issue by dogsworth** [DavidBurkett/Builderberg#20]
Please add an options dialog for custom generated code including `hash()`, `equals()`, and `toString()`.

**Comment by DavidBurkett** [comment]
What do you mean by "options dialog"? As of builderberg 1.1.0, you can annotate classes with @BuilderOptions(generateHashCode = false, generateEquals = false, generate toString=false) and then they won't be generated. If you want to then implement custom versions, implement them manually and annotate the methods with @CustomLogic.
