### ISSUE TITLE
Fix hashCode method generation to guard against NullPointerException

### ISSUE THREAD

**Issue by dogsworth** [DavidBurkett/Builderberg#25]
There is a currently a potential bug where the generated `hashCode()` method will throw a `NullPointerException`. Consider the following generated code:
```
public int hashCode() {
    int result = 17;
    result = 31 * result + firstName.hashCode();
    result = 31 * result + middleName.hashCode();
    result = 31 * result + lastName.hashCode();
    return result;
}
```

If middle name is null, this will throw a `NullPointerException`. Please use `Objects.hashCode()` as it will convert a null value to the hash code of zero.

**Comment by DavidBurkett** [comment]
This is fixed in 1.1.0
