### ISSUE TITLE
When using BuilderOption deserializable and you choose DeserializationType.jackson @JsonProperty("hardwareIdType") should be used in the generated constructor

### ISSUE THREAD

**Issue by MattTYXM** [DavidBurkett/Builderberg#26]

**Comment by DavidBurkett** [comment]
I was aware of this limitation when I developed it, but I was lazy since there's an easy workaround for most cases (name the variable the same as the property name). Pull requests welcome.

**Comment by DavidBurkett** [comment]
I got ambitious and implemented it. It will be in release 1.1.0
