### ISSUE TITLE
Don't generate Getters if field is public final.

### ISSUE THREAD

**Issue by normano** [DavidBurkett/Builderberg#29]
This is good stuff! I am wondering since I have public final fields on data objects that the getters not be generated.  BuilderOptions could have an option there for turning on/off the behavior.

**Comment by DavidBurkett** [comment]
If you make your fields static, it should skip generation for them if my memory serves correctly. This sounds like it would fit your use-case.

**Comment by normano** [comment]
public final static means I can only set it once for the lifetime of the JVM though. :(

**Comment by DavidBurkett** [comment]
I assumed you were using it for a constant. You're wanting a setter/with method for it, but not a getter? That seems bizarre.

**Comment by normano** [comment]
With final there is no setter though. It is an immutable class. The getter is the field itself, so no need for a getter method.

**Comment by normano** [comment]
for example

public class Car {
  public final int mph;
  public Car(builder) {
   mph = builder.mph;
  }

  // No getter for the mph in the Car class

  public class Builder {
    int mph; // accessibility here doesn't matter
    public Builder withMph(int mph) {
      this.mph = mph;
    }
  }
}

**Comment by DavidBurkett** [comment]
Yes, I was talking about the setter in the Builder object (withMph). It's not a best practice to make mph public in your case. The only time I could probably justify making a variable public like that would be if it's a constant, in which case I would expect it to be static as well. I appreciate your suggestion, but I don't think I'll be implementing it at this time. The generated getter shouldn't hurt anything, and it would not be backward-compatible to remove it. I also prefer to not add a BuilderOption for something that's generally considered a poor practice.

**Comment by DavidBurkett** [comment]
I'm closing this for now, but if you believe I'm misunderstanding your scenario, feel free to re-open it.
