### ISSUE TITLE
Add ability to build from another built instance

### ISSUE THREAD

**Issue by MattTYXM** [DavidBurkett/Builderberg#33]
"A" is a class that has had the builder generated
"a" is an instance of A

A newA = A.builder(a).withFieldOne("someNewValue").build();

"newA" has all of the same values as "a" but "fieldOne" has been updated

**Comment by DavidBurkett** [comment]
This would be cool. I'll work on implementing this for the 1.1.1 release

**Comment by DavidBurkett** [comment]
This has been implemented and will be available in the 1.1.1 release.
